services:
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=user_service_db_docker
      - POSTGRES_USER=user_service_db_name_docker
      - POSTGRES_PASSWORD=user_service_db_password_docker
    ports:
      - "5432:5432"
    volumes:
      - user_db:/var/lib/postgresql/data

  redis:
    image: redis:8.4
    ports:
      - "6379:6379"

  user-service-app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL_DOCKER=jdbc:postgresql://postgres:5432/user_service_db_docker
      - DB_USERNAME_DOCKER=user_service_db_name_docker
      - DB_PASSWORD_DOCKER=user_service_db_password_docker

volumes:
  user_db: